# Replace the text below to customize your site
site_name: Everardo Castro - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Everardo Castro
copyright: Copyleft 2023 "Student Name" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - About: about/me.md
  - Reflections :
      - Term 1:
          - Landing: term1/01-Landing.md 
          - Design Studio: 
             - Design Studio: term1/02-Design Studio.md
             - Deform your Face: term1/02-Design Intervention.md
             - Pulse: term1/02-Pulse.md
          - AoWS: term1/03-Atlas of Weak Signals.md
          - Documenting Design: term1/04-Documenting Design.md
          - The Machine Paradox: 
             - Forensic Report: term1/05-Forensic Report.md
             - Triggered: term1/05-Triggered.md
          - Living with your own ideas: term1/06-Living with your own ideas.md
          - Biology Zero: term1/07-Biology Zero.md
          - Agri Zero: term1/08-Agriculture Zero.md
          - Design With Others: term1/09-Design With Others.md
          - Extended Intelligences: term1/10-Extended Intelligences.md

      - Term 2:
          - Design Studio 2:
            - Chaos Fungorum: term2/01a-Chaos Fungorum.md
          - Designing in a State of Climate Emergency: term2/01-Designing in a State of Climate Emergency.md
          - Future Talks: 
            -  Design with Values: term2/02-Design with Values.md
          - Designing with Collective Intelligences: term2/03-Fair Futures.md
          - Digital Prototyping for Design: 
            - Laser Cut: term2/04-Laser.md
            - Paste Printing: term2/04a-3D.md
            - CNC Milling: term2/04b-CNC.md
          - Measuring the World: term2/05-Measuring the World.md
          - Micro Challenges: 
            - Myco Farm: term2/06-Myco Farm.md
          - Extended Intelligences: term2/07-Extended Intelligences.md
          - Communicating Ideas: term2/08-Communicating ideas.md
      - Master project:
          - Initial ideas: project/project.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black
    accent: red
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
